[package]
name = "junit-report"
version = "0.2.1"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]
description = "Create JUnit compatible XML reports."
license = "MIT"
repository = "https://github.com/bachp/junit-report-rs"
keywords = ["junit", "xunit", "xml", "report"]
readme = "README.md"
edition = "2018"

[dependencies]
chrono = "0.4.11"
xml-rs = "0.8.2"
derive-getters = "0.1.0"

[dev-dependencies]
commandspec = "0.12.2"
doc-comment = "0.3.3"
