[package]
name = "junit-report"
version = "0.1.0"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]
description = "Create JUnit compatible XML reports."
license = "MIT"
repository = "https://github.com/bachp/junit-report-rs"

[dependencies]
chrono = "0.4.6"
xml-rs = "0.8.0"
