[package]
name = "junit-report"
version = "0.1.1"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]
description = "Create JUnit compatible XML reports."
license = "MIT"
repository = "https://github.com/bachp/junit-report-rs"
keywords = ["junit", "xunit", "xml", "report"]
readme = "README.md"

[dependencies]
chrono = "0.4.6"
xml-rs = "0.8.0"

[dev-dependencies]
commandspec = "0.11"
